2025-02-23 13:32:06,922 INFO    MainThread:12940 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-23 13:32:06,922 INFO    MainThread:12940 [wandb_setup.py:_flush():67] Configure stats pid to 12940
2025-02-23 13:32:06,922 INFO    MainThread:12940 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Gilad\.config\wandb\settings
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Gilad\Markman Dropbox\Gilad Markman\Python\SpaceShipRide\wandb\settings
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Gilad\Markman Dropbox\Gilad Markman\Python\SpaceShipRide\wandb\run-20250223_133206-REINFORCE-continuous 99\logs\debug.log
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Gilad\Markman Dropbox\Gilad Markman\Python\SpaceShipRide\wandb\run-20250223_133206-REINFORCE-continuous 99\logs\debug-internal.log
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:init():761] calling init triggers
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'name': 'REINFORCE-continuous 99', 'device': 'cpu', 'policy_model': 'REINFORCE_Network(\n  (linear1): Linear(in_features=14, out_features=256, bias=True)\n  (Relu): LeakyReLU(negative_slope=0.01)\n  (linear2): Linear(in_features=256, out_features=256, bias=True)\n  (linear3): Linear(in_features=256, out_features=2, bias=True)\n  (mean_layer): Linear(in_features=256, out_features=2, bias=True)\n  (std_layer): Linear(in_features=256, out_features=2, bias=True)\n)', 'gamma': 0.99, 'lr': 0.001, 'entropy_coe': 0.1, '_wandb': {}}
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:init():784] starting backend
2025-02-23 13:32:06,923 INFO    MainThread:12940 [wandb_init.py:init():788] sending inform_init request
2025-02-23 13:32:06,938 INFO    MainThread:12940 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-23 13:32:06,939 INFO    MainThread:12940 [wandb_init.py:init():803] backend started and connected
2025-02-23 13:32:06,941 INFO    MainThread:12940 [wandb_init.py:init():896] updated telemetry
2025-02-23 13:32:06,981 INFO    MainThread:12940 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-23 13:32:07,342 INFO    MainThread:12940 [wandb_init.py:init():995] starting run threads in backend
2025-02-23 13:32:07,386 INFO    MainThread:12940 [wandb_run.py:_console_start():2377] atexit reg
2025-02-23 13:32:07,386 INFO    MainThread:12940 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-23 13:32:07,386 INFO    MainThread:12940 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-23 13:32:07,386 INFO    MainThread:12940 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-23 13:32:07,388 INFO    MainThread:12940 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-23 13:32:34,366 WARNING MsgRouterThr:12940 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Gilad\.virtualenvs\SpaceShipRide-0PfYb7R8\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gilad\.virtualenvs\SpaceShipRide-0PfYb7R8\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gilad\.virtualenvs\SpaceShipRide-0PfYb7R8\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gilad\.virtualenvs\SpaceShipRide-0PfYb7R8\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gilad\.virtualenvs\SpaceShipRide-0PfYb7R8\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-23 13:32:34,366 INFO    MsgRouterThr:12940 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
